name: Simple FTP Test

on:
  workflow_dispatch:
  push:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Create test file
      run: echo "TEST - $(date)" > TEST_FILE_PLEASE_FIND_ME.txt && cat TEST_FILE_PLEASE_FIND_ME.txt
    
    - name: Upload test file
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        port: 21
        server-dir: ./
        local-dir: ./
        exclude: |
          **/*
        include: |
          TEST_FILE_PLEASE_FIND_ME.txt
    
    - name: Test Complete
      run: echo "Look for TEST_FILE_PLEASE_FIND_ME.txt in Hostinger File Manager!"